services:
  app:
    build: .
    image: streamlit-clientes:1.0
    container_name: app-clientes
    ports:
      - "8501:8501"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: clientesdb
      DB_USER: user
      DB_PASSWORD: pass
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16
    container_name: postgres-clientes
    environment:
      POSTGRES_DB: clientesdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d clientesdb"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
