apiVersion: v1
kind: Service
metadata:
  name: app-config-service
  namespace: curso-k8s-config
spec:
  type: NodePort
  selector:
    app: app-config
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30081
